name: release
on:
  workflow_dispatch:
    inputs:
      version:
        description: VERSION
        required: false
jobs:
  pipeline:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: true
    - name: Build
      uses: docker://buildpack-deps:trusty
      with:
        args: sh -c "curl -sS https://setup.inaccel.com/repository | sh && apt install coral-api && make"
    - name: Package Debian
      uses: docker://goreleaser/nfpm
      env:
        VERSION: ${{ github.event.inputs.version }}
      with:
        args: pkg --packager deb
    - name: Package RPM
      uses: docker://goreleaser/nfpm
      env:
        VERSION: ${{ github.event.inputs.version }}
        RELEASE: 1
      with:
        args: pkg --packager rpm
    - name: Push Debian
      uses: cloudsmith-io/action@master
      with:
        api-key: ${{ secrets.CLOUDSMITH_API_KEY }}
        command: push
        format: deb
        owner: inaccel
        repo: stable
        distro: any-distro
        release: any-version
        file: '*.deb'
    - name: Push RPM
      uses: cloudsmith-io/action@master
      with:
        api-key: ${{ secrets.CLOUDSMITH_API_KEY }}
        command: push
        format: rpm
        owner: inaccel
        repo: stable
        distro: any-distro
        release: any-version
        file: '*.rpm'
